## Bag of Words implementation

-> For each word in vocabulary it counts the number of times word occured in the particular sentence and use it as numerical representation of that sentence

-> CONS : Completely lost the sequential information as it only keeps count of word regardless of the sequence

In [1]:
paragraph = "Beans. I was trying to explain to somebody as we were flying in, that's corn. That's beans. And they were very impressed at my agricultural knowledge. Please give it up for Amaury once again for that outstanding introduction. I have a bunch of good friends here today, including somebody who I served with, who is one of the finest senators in the country and we're lucky to have him, your Senator, Dick Durbin is here. I also noticed, by the way, former Governor Edgar here, who I haven't seen in a long time and somehow he has not aged and I have. And it's great to see you, Governor. I want to thank President Killeen and everybody at the U of I System for making it possible for me to be here today. And I am deeply honored at the Paul Douglas Award that is being given to me. He is somebody who set the path for so much outstanding public service here in Illinois. Now, I want to start by addressing the elephant in the room. I know people are still wondering why I didn't speak at the commencement."

In [4]:
# using sentence tokenizer to break paragraph into sentences
import nltk 
from nltk.tokenize import sent_tokenize

sentences = sent_tokenize(paragraph)

# printing sentences
for i, sentence in enumerate(sentences):
    print(i, sentence)

0 Beans.
1 I was trying to explain to somebody as we were flying in, that's corn.
2 That's beans.
3 And they were very impressed at my agricultural knowledge.
4 Please give it up for Amaury once again for that outstanding introduction.
5 I have a bunch of good friends here today, including somebody who I served with, who is one of the finest senators in the country and we're lucky to have him, your Senator, Dick Durbin is here.
6 I also noticed, by the way, former Governor Edgar here, who I haven't seen in a long time and somehow he has not aged and I have.
7 And it's great to see you, Governor.
8 I want to thank President Killeen and everybody at the U of I System for making it possible for me to be here today.
9 And I am deeply honored at the Paul Douglas Award that is being given to me.
10 He is somebody who set the path for so much outstanding public service here in Illinois.
11 Now, I want to start by addressing the elephant in the room.
12 I know people are still wondering why I 

In [6]:
# using word tokenizer to break sentences into words 
from nltk.tokenize import word_tokenize 

tokenized_sentences = [word_tokenize(sentence) for sentence in sentences]

# printing tokenized sentences
for i, sentence in enumerate(tokenized_sentences):
    print(i, sentence)

0 ['Beans', '.']
1 ['I', 'was', 'trying', 'to', 'explain', 'to', 'somebody', 'as', 'we', 'were', 'flying', 'in', ',', 'that', "'s", 'corn', '.']
2 ['That', "'s", 'beans', '.']
3 ['And', 'they', 'were', 'very', 'impressed', 'at', 'my', 'agricultural', 'knowledge', '.']
4 ['Please', 'give', 'it', 'up', 'for', 'Amaury', 'once', 'again', 'for', 'that', 'outstanding', 'introduction', '.']
5 ['I', 'have', 'a', 'bunch', 'of', 'good', 'friends', 'here', 'today', ',', 'including', 'somebody', 'who', 'I', 'served', 'with', ',', 'who', 'is', 'one', 'of', 'the', 'finest', 'senators', 'in', 'the', 'country', 'and', 'we', "'re", 'lucky', 'to', 'have', 'him', ',', 'your', 'Senator', ',', 'Dick', 'Durbin', 'is', 'here', '.']
6 ['I', 'also', 'noticed', ',', 'by', 'the', 'way', ',', 'former', 'Governor', 'Edgar', 'here', ',', 'who', 'I', 'have', "n't", 'seen', 'in', 'a', 'long', 'time', 'and', 'somehow', 'he', 'has', 'not', 'aged', 'and', 'I', 'have', '.']
7 ['And', 'it', "'s", 'great', 'to', 'see', 'yo

In [12]:
# Now we'll remove stop words and punctuation
from nltk.corpus import stopwords 
nltk.download('stopwords')

# Stop word 
stop_words = stopwords.words('english')

# punctuations 
import string 
punct_string = string.punctuation
puncts = [punct for punct in punct_string]

# Words not to keep 
stop_words_and_puncts = stop_words + puncts 
print(stop_words_and_puncts)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she

[nltk_data] Downloading package stopwords to /Users/umesh/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [38]:
# keeping only meaningfl words in sentences 
preprocessed_sentences = []
for sentence in tokenized_sentences:
    sent = [word.lower() for word in sentence if word not in stop_words_and_puncts]
    preprocessed_sentences.append(sent)

# printing new sentences 
for sentence in preprocessed_sentences:
    print(sentence)

['beans']
['i', 'trying', 'explain', 'somebody', 'flying', "'s", 'corn']
['that', "'s", 'beans']
['and', 'impressed', 'agricultural', 'knowledge']
['please', 'give', 'amaury', 'outstanding', 'introduction']
['i', 'bunch', 'good', 'friends', 'today', 'including', 'somebody', 'i', 'served', 'one', 'finest', 'senators', 'country', "'re", 'lucky', 'senator', 'dick', 'durbin']
['i', 'also', 'noticed', 'way', 'former', 'governor', 'edgar', 'i', "n't", 'seen', 'long', 'time', 'somehow', 'aged', 'i']
['and', "'s", 'great', 'see', 'governor']
['i', 'want', 'thank', 'president', 'killeen', 'everybody', 'u', 'i', 'system', 'making', 'possible', 'today']
['and', 'i', 'deeply', 'honored', 'paul', 'douglas', 'award', 'given']
['he', 'somebody', 'set', 'path', 'much', 'outstanding', 'public', 'service', 'illinois']
['now', 'i', 'want', 'start', 'addressing', 'elephant', 'room']
['i', 'know', 'people', 'still', 'wondering', 'i', "n't", 'speak', 'commencement']


In [39]:
# now we'll make a vocabulary 
word2idx = {}
idx2word = {}

set_of_word = set()

idx = 0
for sentence in preprocessed_sentences:
    for word in sentence:
        if word not in set_of_word:
            word2idx[word] = idx 
            idx2word[idx] = word 
            idx += 1
            set_of_word.add(word)

vocab_size = len(word2idx)
print(f"Size of vocabulary : {vocab_size}")

Size of vocabulary : 80


In [41]:
# Now in bag of words we represent a sentence by this vocabulary (index represent words and filling count of how many time that word appeared in sentence)
import torch
vectors = []

for sent in preprocessed_sentences:
    sent_tensor = torch.zeros((vocab_size))
    for word in sent:
        sent_tensor[word2idx[word]] += 1 
    vectors.append(sent_tensor)

for sentence in vectors:
    print(sentence)


tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.

### Pros of BOW
1) Simplicity - Easy to implement
2) Used for various NLP tasks - text classification, sentiment analysis 

### Cons of BOW
1) Order of word gets lost 
2) Data is sparse computationally inefficient
3) Can't capture meaning of word

## N-Grams

In BOW we consider only one word in vocabulary, but here we can consider n words (consecutive) at one index in vocabulary allowing to keep local context

In [42]:
sentences = ['Machine learning love Umesh Kumar.', 'Umesh Kumar loves Machine learning.']

In [46]:
# splitting into bi-gram in which n=2

bigram_sent = sentences[0].split(' ')
bigram_sent = [bigram_sent[i:i+2] for i in range(len(bigram_sent)-1)]
bigram_sent

[['Machine', 'learning'],
 ['learning', 'love'],
 ['love', 'Umesh'],
 ['Umesh', 'Kumar.']]

In [50]:
unique_bigrams = set()
bigrams_sentences = []
for sentence in sentences:
    sent = sentence.split(' ')
    bigram_sent = [' '.join(sent[i:i+2]) for i in range(len(sent)-1)]
    bigrams_sentences.append(bigram_sent)
    for bigrams in bigram_sent:
        if bigrams not in unique_bigrams:
            unique_bigrams.add(bigrams)

print(f"Total unique bigrams : {len(unique_bigrams)}")

Total unique bigrams : 8


In [51]:
print(unique_bigrams)

{'Umesh Kumar.', 'love Umesh', 'loves Machine', 'Machine learning.', 'learning love', 'Machine learning', 'Kumar loves', 'Umesh Kumar'}


In [52]:
# printing bigram formatted sentences 
for sent in bigrams_sentences:
    print(sent)

['Machine learning', 'learning love', 'love Umesh', 'Umesh Kumar.']
['Umesh Kumar', 'Kumar loves', 'loves Machine', 'Machine learning.']


In [54]:
# now we'll create vector for these sentences 
word2idx = {word:idx for idx, word in enumerate(unique_bigrams)}
idx2word = {idx:word for idx, word in enumerate(unique_bigrams)}

print(word2idx)

{'Umesh Kumar.': 0, 'love Umesh': 1, 'loves Machine': 2, 'Machine learning.': 3, 'learning love': 4, 'Machine learning': 5, 'Kumar loves': 6, 'Umesh Kumar': 7}


In [56]:
vectorized_sent = []

for sent in bigrams_sentences:
    sent_tensor = torch.zeros((len(word2idx)))
    for word in sent:
        sent_tensor[word2idx[word]] += 1
    
    vectorized_sent.append(sent_tensor)

for vector in vectorized_sent:
    print(vector)

tensor([1., 1., 0., 0., 1., 1., 0., 0.])
tensor([0., 0., 1., 1., 0., 0., 1., 1.])
